source 'https://github.com/cppfw/cocoapods-repo.git'

project 'svgdom/svgdom.xcodeproj'

platform :ios, '8.0'

target "svgdom" do
	pod 'utki', '>= 1.1.117'
	pod 'papki', '>= 1.0.91'
	pod 'mikroxml', '>= 0.1.34'
	pod 'cssdom', '>= 0.1.15'
	pod 'r4', '>= 1.0.51'
end
