source 'https://github.com/cppfw/cocoapods-repo.git'

project 'svgdom/svgdom.xcodeproj'

platform :ios, '12.0'

target "svgdom" do
	pod 'utki', '>= 1.1.164'
	pod 'papki', '>= 1.0.93'
	pod 'mikroxml', '>= 0.1.36'
	pod 'cssom', '>= 0.1.19'
	pod 'r4', '>= 1.0.53'
end
